### ISSUE TITLE
Configure through lambda

### ISSUE THREAD

**Issue by mgutz** [mgutz/mapper#6]
From #5 

I was thinking of feature like:

``` javascript
mapper.client.configure(function(client) {
  client.setOptionSync(mysql.FLAG_1, val1);
  client.setOptionSync(mysql.FLAG_2, val2);
  /* ... */
});
```

It may be useful if one wants to control mysql connection (as example, sometimes I need to set MYSQL_OPT_RECONNECT flag). And with such thing we can avoid much code if we'd implement different client features. What do you think about such configure(fn) feature?

**Comment by estliberitas** [comment]
Okay, I'll do this thing in 24 hrs. ;)

**Comment by mgutz** [comment]
Implemented as an optional config property

```
var config = { user: 'foo', password: 'secret' };
config.configureFn = function(client) {
  client.setOptionSync(mysql.MYSQL_OPT_RECONNECT, 1);
};

Mapper.connect(config);
```

**Comment by estliberitas** [comment]
Ok. You 24hrs are much more fast than mine xD Thanks!
